FROM python:3.9
WORKDIR /var/lib/jenkins/workspace/mb-checker
COPY requirements.txt requirements.txt
RUN [ "pip", "install",  "-r", "requirements.txt" ]
COPY . .
RUN chmod a+x buildcodes.sh
CMD [ "buildcodes.sh" ]