FROM python:3.9
WORKDIR /mb-checker
COPY requirements.txt requirements.txt
RUN [ "pip", "install",  "-r", "requirements.txt" ]
COPY ./Bookmarks ./
RUN [ "mkdir", "work_dir" ]
CMD [ "python", "/mb-checker/scanJSON.py" ]