FROM python:3.9
WORKDIR /mb-checker
ADD requirements.txt .
RUN [ "pip", "install",  "-r", "requirements.txt" ]
RUN [ "mkdir", "work_dir" ]
#CMD [ "pwd" ]
CMD [ "ls", "-l" ]
#CMD [ "python", "/mb-checker/scanJSON.py" ]